### ISSUE TITLE
Update yaru* lib deps

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-flutter-plugins#325]
Wanted to updated the app center with yaru updates but this conflict appears: apparently this lib here depends on all three yaru libs. This feels kind of inconvenient. Would it be possible to remove those deps here?

@d-loose

**Comment by d-loose** [comment]
We're sticking with flutter 3.10.6 for now and will probably take care of updating dependencies in all kinds of places after the 23.10 release

**Comment by Feichtmeier** [comment]
ah ok
well I can see if I could make small design improvements without the yarus then

anyways, are those widgets here eventually candidates for transfering them to yaru_widgets at some point?
https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_widgets/lib/src
I think those are the only ones using the yaru libs in this repo

**Comment by spydon** [comment]
This is done
